### ISSUE TITLE
Missing symbols and notation in MusicXML export.

### ISSUE THREAD

**Issue by Skippern** [helge17/tuxguitar#289]
I use TuxGuitar mainly on Linux but also on Windows to view and edit GP tabs, and export to MusicXML for use in Rocksmith+ Workshop. I notice that a lot of the notation is missing in the exported MusicXML.

Missing these symbols makes the process of importing songs to Rocksmith+ very cumbersome.

Below list is an observation of missing symbols and notations, compiled with help of different users of Rocksmith+ Workshop:

Tuning:
* [ ] Tuning-Alter (sharps / flats in tuning)
* [ ] Capo

Bends:
* [ ] Bend
* [ ] Bend + Release
* [ ] PreBend
* [ ] PreBend + Bend
* [ ] PreBend + Release

Repeats:
* [ ] Repeats
* [ ] Alternative Endings

Note statuses:
* [ ] Start Tie
* [ ] Ghost Note
* [ ] Accented Note
* [ ] Heavily accented Note
* [ ] Staccato
* [ ] Palm Mute
* [ ] Dead note (FHM)
* [ ] Let Ring
* [ ] Natural harmonics
* [ ] Artificial harmonics
* [ ] Pinch harmonics - technically not supported in Tux.

Slides:
* [ ] Legato Slide
* [ ] Shift Slide
* [ ] Slide in from below
* [ ] Slide in from above
* [ ] Slide out downward
* [ ] Slide out upwards

Techniques:
* [ ] Hammer on
* [ ] Pull off
* [ ] Tap
* [ ] Slap
* [ ] Pop

Picking technique:
* [ ] Tremolo
* [ ] Trill

**Comment by guiv42** [comment]
Hi,

which version of TuxGuitar are you using? We are currently working on musicXML export, so it is constantly evolving.
In latest snapshot, tuning-alter, repeats and alternative endings should be OK. Lyrics are in progress (#282). Drums parts are still buggy (I'm currently working to fix this).

Then, you're right there's still a lot to do.

However it won't be possible to export everything, e.g. because of limitations in musicXML format itself. I haven't looked in details at all your list, but for example the description of bend effect available in [musicXML](https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/bend/) is not detailed enough to export all information available in TuxGuitar.
Some other fields might be quite tricky, because the internal representation of data in TuxGuitar really differs from the musicXML data structure (thinking of "hammer-on/pull-off" for example).

**Comment by Skippern** [comment]
I was using 1.5.6 on the windows but upgraded to 1.6.1 today, on the Linux I currently use 1.2 which is the version served through Ubuntu packet manager.

**Comment by guiv42** [comment]
OK, all improvements of musicXML export have been implemented *after* 1.6.1.
So if you want to have a look you will need to install latest pre-release (note that .deb packages are delivered!). If you go for a pre-release, I recommend to use SWT version (not JFX), and to update on a regular basis. Typically musicXML export is progressing these days.

**Comment by profOnno** [comment]
Great TODO list.

@Skippern I'm using Rocksmit 2014 Remasterd, it's is great with CDLC's, so I understand the requested enhancement.
I'll try check some of the boxes.

**Comment by Skippern** [comment]
The workflow in Rocksmith+ Workshop is a little different than Editor on Fire, as I recall EOF could import directly older versions of GP files. Rocksmith+ Workshop doesn't allow any of the GP formats nor TuxGuitar format, so I have to convert all tabs to MusicXML. Current pre-release version (I checked 2024-03-15 and 2024-03-17) exported MusicXML does not import correctly at all into Workshop, 1.6.1 import the notes but no notation symbols.

I will continue to test as new pre-releases comes out.

**Comment by guiv42** [comment]
just merged:
- #282
- #296: a first fix for drums track, just to make sure the xsd schema is not violated

drums track export is still incorrect.

**Comment by guiv42** [comment]
I'm adding a tag "good first issue" here, since the required modifications should be local to [MusicXMLWriter](https://github.com/helge17/tuxguitar/blob/master/desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLWriter.java).

If someone wants to add new MusicXML tags, please write it explicitly in this discussion to avoid concurrent implementations.

Useful data for newcomers:
- musicXML specification: https://www.musicxml.com/for-developers/
- specification of `<score-partwise>` xml node content: https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/score-partwise/

Procedure to check that generated MusicXML file validates the xsd schema:
1. download XSD schema: https://github.com/w3c/musicxml/releases/tag/v4.0, and extract archive.
2. patch file "schema/musicxml.xsd" as follows: replace
```
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.musicxml.org/xsd/xml.xsd"/>
	<xs:import namespace="http://www.w3.org/1999/xlink" schemaLocation="http://www.musicxml.org/xsd/xlink.xsd"/>
```
by
```
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
	<xs:import namespace="http://www.w3.org/1999/xlink" schemaLocation="xlink.xsd"/>
```

([source](https://blog.karimratib.me/2020/11/17/validate-musicxml.html) for this patch).

3. to check validity of one musicxml file in Linux:
```
$ xmllint --schema schema/musicxml.xsd my_test_file.musicxml --noout
```

This should return "my_test_file.musicxml validates"

For testing, a possibility is to open exported file with another software capable of reading musicXML file format. MuseScore can do the job pretty well. Just ignore if it displays some red notes (see [this post](https://github.com/helge17/tuxguitar/issues/169#issuecomment-1971897274)), or reallocate tracks to the correct instrument in MuseScore.

**Comment by tdan** [comment]
hey @guiv42 I can help with this issue as well.

**Comment by tdan** [comment]
Hi everyone,

I've implemented a basic bend and tapping notation in MusicXML and would like to see if it works as expected. While the generated files seem valid according to xmllint, MuseScore doesn't display the scores correctly.

To diagnose the issue, I tried adding bends and taps in MuseScore and exporting them as MusicXML for comparison. Unfortunately, the export process seems to drop these effects.

Does anyone recommend alternative programs that can open and display MusicXML 4 files effectively? I'm using Fedora, so options might be limited.

@Skippern , if you have a chance, could you test these files on Rocksmith to see if they import correctly?

Thanks!

[Eric Clapton - Wonderful Tonight (ver 4).musicxml.txt](https://github.com/helge17/tuxguitar/files/15449385/Eric.Clapton.-.Wonderful.Tonight.ver.4.musicxml.txt)
[Tapping Exercise - The Bach Lick.musicxml.txt](https://github.com/helge17/tuxguitar/files/15449386/Tapping.Exercise.-.The.Bach.Lick.musicxml.txt)

**Comment by guiv42** [comment]
Hi @tdan 
I did not try, but a quick search of "musicxml viewer" on github led me [there](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay), possibly an interesting option

**Comment by Skippern** [comment]
> 
> @Skippern , if you have a chance, could you test these files on Rocksmith to see if they import correctly?
> 
Still not loading in Rocksmith+ Workshop. I think there is a basic syntax mismatch, as I get all tracks duplicated, and huge discrapency between note lengths, I was not able to see if bends or taps loaded as the Tapping Exercise overshot the song, and Eric Clapton gave me the first note at the end of the song.

**Comment by guiv42** [comment]
> I get all tracks duplicated

I'm responsible for this (#257). Historically data related to score and tab were mixed in an inconsistent manner: a guitar track was exported as a *score* with 6 *lines* (see [musescore screenshot](https://github.com/helge17/tuxguitar/issues/169#issuecomment-1967830245)).
Now it exports a *score* with 5 *lines* **plus** a *tab* with N *strings* for each track. I didn't find a way to encode both score&tab within one single musicXML track.
Any suggestion welcome!

> huge discrapency between note lengths

I don't explain this. @Skippern could you please test this very basic file?
[C.tar.gz](https://github.com/helge17/tuxguitar/files/15454747/C.tar.gz)


@tdan: better separate problems. If you want to test bends and tapping, please define 1 basic .tg test file for each feature. In each file just one track and just a few notes, to ease the manual analysis of output files.

**Comment by Skippern** [comment]
If test files are limited to a few measures, than I can load them on any song just to see if the technique is loaded correctly or not.

**Comment by guiv42** [comment]
Sorry I don't understand. Could you please check if you still have "huge discrepancies between note lengths" in the basic example I provided?
Here is how it looks in TuxGuitar, and after importing .musicxml in MuseScore (forget the red notes):
![C_tuxguitar](https://github.com/helge17/tuxguitar/assets/129443524/923f1647-17dc-4bbd-a214-97b06bb6e97b)
![C_musescore](https://github.com/helge17/tuxguitar/assets/129443524/48118631-3dec-4e35-a110-d57e5bc39a37)

**Comment by guiv42** [comment]
Okay... That's unexpected.
So we've got to fix that before trying to go any further about bends/tapping or whatever

**Comment by Skippern** [comment]
![C-expected](https://github.com/helge17/tuxguitar/assets/802652/20889716-fcff-4ce8-af50-459934ac0583)
Here is a handwritten bar as expected from that .tg file

**Comment by guiv42** [comment]
@Skippern could you please try to open the following file?
I recreated the same file from MuseScore, then exported to musicxml (so, TuxGuitar is not involved here)
[C_musescore.tar.gz](https://github.com/helge17/tuxguitar/files/15454924/C_musescore.tar.gz)

**Comment by Skippern** [comment]
![Cmusescore](https://github.com/helge17/tuxguitar/assets/802652/ff169ba7-6287-462e-909b-e9103c244484)
Closer but also with missing notes, the sustain on the quarter note, I've never figured out when they import and when not, so that is not a big issue, more concerned about the missing notes from the chord there, but first three notes imports correctly

**Comment by guiv42** [comment]
This is really puzzling... Looking at both musicxml files created by TuxGuitar and MuseScore, notes duration seem OK to me.
TuxGuitar: measure division is defined to 960, first two notes duration is 480, third note is 960, last is 1920
MuseScore: measure division is defined to 2, first two notes duration is 1, third note is 2, last is 4

Could it be an import issue in Rocksmith+ Workshop??

**Comment by Skippern** [comment]
It is possible, I could try to reach out to  Ubisoft Rocksmith+ dev team, but don't expect any reply. Could be helpful if they shared their MusicXML technical template.

**Comment by guiv42** [comment]
Hi, and thank you for the feedback.
I'll try to understand how to combine the 2 staffs into one single track and this duration issue
@ffio1 : unfortunately I cannot use the example you provided as a model, as it violates the musicXML 4.0 schema
`C_SinglePart_5-27-24.musicxml:162: element staff: Schemas validity error : Element 'staff': This element is not expected. Expected is one of ( notations, lyric, play, listen ).`
(same error repeated several times)

Could you please provide a simple valid example?

**Comment by guiv42** [comment]
understood: need to delete `<part id="P1-tab">` node
[C_SinglePart_5-27-24_guiv.tar.gz](https://github.com/helge17/tuxguitar/files/15458893/C_SinglePart_5-27-24_guiv.tar.gz)

**Comment by ffio1** [comment]
Yep, that imported properly into Rocksmith Workshop!

![image](https://github.com/helge17/tuxguitar/assets/12983101/1c269925-75b6-4289-b8bf-5a89f0468648)

Also verified it imports into Musescore (v4.2.1):
![image](https://github.com/helge17/tuxguitar/assets/12983101/59d3f503-e8a1-416a-b830-313d61229e43)

And Guitar Pro (v8.1.1):
![image](https://github.com/helge17/tuxguitar/assets/12983101/16f6c3e2-a26f-4ffe-8760-157e845f764d)

**Comment by guiv42** [comment]
OK, thanks. Next step is to produce such a file from TuxGuitar. I'm trying.

**Comment by guiv42** [comment]
That should be OK now
After #398 , my example "C.tg" file (in [this post](https://github.com/helge17/tuxguitar/issues/289#issuecomment-2133222990)) produces exactly the expected musicxml file (in [this post](https://github.com/helge17/tuxguitar/issues/289#issuecomment-2133898194)).
That should fix the import into Rocksmith Workshop

**Comment by guiv42** [comment]
forgot an important point: thank you very much @ffio1 for the detailed explanation!

**Comment by guiv42** [comment]
@tdan this will probably create merge conflicts in your dev branch, sorry for that.
Bends and Tapping should be inserted in[`<technical>`](https://github.com/helge17/tuxguitar/blob/072d50a3b2add90fe9e5731275f48078ad536e8f/desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLWriter.java#L361) xml node I think

**Comment by Skippern** [comment]
Note values are correct in the import I tested in Rocksmith Workshop, the issues I had now was probably more linked to the quality of the UG gp5 tabs I used. I would say the export function is good enough to start testing the symbols and notations. 
[The GP5 file and resulting MusicXML](https://github.com/helge17/tuxguitar/files/15475739/Fine.Young.Cannibals.-.She.Drives.Me.Crazy.zip)

**Comment by tdan** [comment]
> @tdan this will probably create merge conflicts in your dev branch, sorry for that. Bends and Tapping should be inserted in[`<technical>`](https://github.com/helge17/tuxguitar/blob/072d50a3b2add90fe9e5731275f48078ad536e8f/desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLWriter.java#L361) xml node I think

Hey don't worry :). I'm glad we were able to fix this issue in such a timely manner. Yep, Bends & Tap are in <technical> along with a few others. I'm using this reference [here](https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/) to implement each effect.

Many thanks to @ffio1 for the MusicXML expertise & @Skippern for testing!

**Comment by guiv42** [comment]
multi-voice is now supported (#453)

**Comment by ffio1** [comment]
I recently got some free time, and I'll try to help address this issue. I'll create a PR soon™ that addresses a lot of MusicXML export issues, as well as some GPX import issues.

Currently the MusicXML pile has: 
- Fixes a bug with repeats being exported with the incorrect number of repeats (repeat count - 1 was being exported).
- Alternate endings to repeats
- Capo / Offset
- Dynamics
- Markers / Rehearsals
- Harmonics*
- Slides
- Accent
- Heavily accented
- Staccato
- HO/PO*
- Bends / Prebends / Bend-Releases
- Palm Mute / Dead Note
- Ghost Note

And the GPX pile has:
- Import Capo
- Import Let-Ring status (this is available in TuxGuitar, but not in the MusicXML spec).

* - I'm still working on these, and this list will likely grow as I find more things that need to be fixed.

**Comment by guiv42** [comment]
Initial [description](https://github.com/helge17/tuxguitar/issues/289#issue-2190238792) provided a list of features to implement.
If someone has some time to spend on this issue, it could be interesting to have a synthesis of what has been already implemented and what not.
For newcomers: [this post](https://github.com/helge17/tuxguitar/issues/289#issuecomment-2024079277) contains useful information to implement these features ([MusicXMLWriter](https://github.com/helge17/tuxguitar/blob/master/desktop/TuxGuitar-musicxml/src/app/tuxguitar/io/musicxml/MusicXMLWriter.java) has moved since this post was written)

**Comment by einhander** [comment]
Text entered using the Beat -> Insert Text command is missing in the MusicXML export file.

**Comment by AzazelSensei** [comment]
Opened https://github.com/helge17/tuxguitar/pull/1187 for Beat -> Insert Text in the MusicXML export.
